// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGXUpNg-vmpUIkHGnEj3KMqBkQrK_kYzg',
    appId: '1:898179316329:web:1788179c8c62b8694580f8',
    messagingSenderId: '898179316329',
    projectId: 'resdhan-earnings',
    authDomain: 'resdhan-earnings.firebaseapp.com',
    storageBucket: 'resdhan-earnings.appspot.com',
    measurementId: 'G-1DGJ385DQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxcDRvH0nOExp0zQA6wkqZxkAiLVJ8Rk',
    appId: '1:898179316329:android:f993ed3132ab79ad4580f8',
    messagingSenderId: '898179316329',
    projectId: 'resdhan-earnings',
    storageBucket: 'resdhan-earnings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxusQk0AhRTdkY6VVg7Cwy4YgnRZ0PHgc',
    appId: '1:898179316329:ios:e61e2b24d2b022f34580f8',
    messagingSenderId: '898179316329',
    projectId: 'resdhan-earnings',
    storageBucket: 'resdhan-earnings.appspot.com',
    iosBundleId: 'com.kaizenapps.resdhan',
  );
}
